package entity;
// Generated Jan 22, 2019 1:40:07 AM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Departs generated by hbm2java
 */
@Entity
@Table(name = "Departs")
public class Departs implements java.io.Serializable {

	private int id;
	private String name;

	public Departs() {

	}

	public Departs(int id) {
		this.id = id;
	}
	public Departs(String name) {
		this.name = name;
	}
	public Departs(int id,String name) {
		this.id = id;
		this.name = name;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
