package entity;
// Generated Jan 22, 2019 1:40:07 AM by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Records generated by hbm2java
 */
@Entity
@Table(name = "Records", schema = "dbo", catalog = "Personnel")
public class Records implements java.io.Serializable {

	private int id;
	private Boolean type;
	private String reason;
	private Date date;
	private Staffs staffId;

	public Records() {
	}
	public Records(int id) {
		this.id = id;
	}
	
	public Records(Boolean type, String reason, Date date, Staffs staffId) {
		super();
		this.type = type;
		this.reason = reason;
		this.date = date;
		this.staffId = staffId;
	}
	public Records(int id, Boolean type, String reason, Date date, Staffs staffId) {
		super();
		this.id = id;
		this.type = type;
		this.reason = reason;
		this.date = date;
		this.staffId = staffId;
	}
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Type", nullable = false)
	public Boolean getType() {
		return this.type;
	}

	public void setType(Boolean type) {
		this.type = type;
	}

	@Column(name = "Reason", nullable = false)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "Date", nullable = false)
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern="MM/dd/yyyy")
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@ManyToOne
	@JoinColumn(name = "StaffId", nullable = false)
	public Staffs getStaffId() {
		return this.staffId;
	}

	public void setStaffId(Staffs staffId) {
		this.staffId = staffId;
	}

}
