package entity;
// Generated Jan 22, 2019 1:40:07 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * Staffs generated by hbm2java
 */
@Entity
@Table(name = "Staffs", schema = "dbo", catalog = "Personnel")
public class Staffs implements java.io.Serializable {

	private int id;
	private String name;
	private boolean gender;
	private Date birthday;
	private String photo;
	private String email;
	private String phone;
	private double salary;
	private String notes;
	private Departs departId;

	public Staffs() {
	}
	public Staffs(int id) {
		this.id = id;
	}
	

	public Staffs( String name, boolean gender, Date birthday, String photo, String email, String phone,
			double salary, String notes, Departs departId) {
		this.name = name;
		this.gender = gender;
		this.birthday = birthday;
		this.photo = photo;
		this.email = email;
		this.phone = phone;
		this.salary = salary;
		this.notes = notes;
		this.departId = departId;
	}
	public Staffs(int id, String name, boolean gender, Date birthday, String photo, String email, String phone,
			double salary, String notes, Departs departId) {
		this.id = id;
		this.name = name;
		this.gender = gender;
		this.birthday = birthday;
		this.photo = photo;
		this.email = email;
		this.phone = phone;
		this.salary = salary;
		this.notes = notes;
		this.departId = departId;
	}
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "Name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Gender", nullable = false)
	public boolean isGender() {
		return this.gender;
	}

	public void setGender(boolean gender) {
		this.gender = gender;
	}

	@Column(name = "Birthday", nullable = false)
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern="MM/dd/yyyy")
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "Photo", nullable = false)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@Column(name = "Email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Phone", nullable = false)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "Salary", nullable = false, precision = 53, scale = 0)
	public double getSalary() {
		return this.salary;
	}

	public void setSalary(double salary) {
		this.salary = salary;
	}

	@Column(name = "Notes")
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@ManyToOne
	@JoinColumn(name = "DepartId", nullable = false)
	public Departs getDepartId() {
		return this.departId;
	}

	public void setDepartId(Departs departId) {
		this.departId = departId;
	}
	@Override
	public String toString() {
		return "Staffs [id=" + id + ", name=" + name + ", gender=" + gender + ", birthday=" + birthday + ", photo="
				+ photo + ", email=" + email + ", phone=" + phone + ", salary=" + salary + ", notes=" + notes
				+ ", departId=" + departId + "]";
	}

}
